import { ArrowUpRight, ArrowDownRight } from 'lucide-react';
import { PageHeader } from '../components/PageLayout';
import { Eyebrow } from '../components/Motion';
import SpotlightCard from '../components/reactbits/SpotlightCard';
import { Link } from '../context/RouterContext';

export default function AboutUs() {
    return <><PageHeader eyebrow="A SMALL TOOL. A SIMPLE IDEA." title="Keep the good stuff." description="We built YTSaver for the videos you want to watch again, and the audio you want to take along." /><section className="about-story container"><div className="about-statement"><span className="mono">WHY WE’RE HERE</span><h2>The internet is full of great things.<br /><span className="muted-heading">Saving them should be simple.</span></h2><ArrowDownRight size={48} /></div><div className="about-prose"><p>A tutorial you’ll need tomorrow. A talk you want to listen to on a walk. A video you made and want to keep.</p><p>YTSaver makes those moments easy to save. One link, a choice of formats, and a download straight to your device. No account to create. No extra software.</p><p>We think a useful tool should get out of your way. So we keep the process short, the options clear, and your media off our server’s disk.</p><Link href="/" className="inline-link">Find your next offline moment <ArrowUpRight size={16} /></Link></div></section><section className="about-principles container"><Eyebrow>A FEW THINGS WE CARE ABOUT</Eyebrow><div className="principle-grid">{[['01','Less friction.','No sign-up, no installation. Open your browser and get started.'],['02','Your choice.','Video or audio. A smaller file or a higher resolution. Pick what works for you.'],['03','Respect the source.','Good work deserves respect. Save only content you own or have permission to download.']].map(([number,title,text]) => <SpotlightCard className="principle" spotlightColor="rgba(160, 110, 240, 0.15)" key={number}><span className="mono">{number} /</span><h3>{title}</h3><p>{text}</p></SpotlightCard>)}</div></section><div className="about-contact container"><h2>Something on your mind?</h2><Link href="/contact" className="inline-link">We’d like to hear it <ArrowUpRight size={18} /></Link></div></>;
}
